const SHEET_ID='2PACX-1vQpGhlw4liRjnPuOJde52Xv2yh_7zvYRJVQq7aT1fXHttSGEnsR62DWy1qLdnjlNMff3vLgKKWbhXGw';
const WORKBOOK_URL=`https://docs.google.com/spreadsheets/d/e/${SHEET_ID}/pubhtml`;
const SOURCES={impressions:'106908487',clicks:'1910465866',position:'1185312213'};
const COLORS={impressions:'#194f3d',clicks:'#4e83a7',position:'#8b78a8',ctr:'#e68753'};
const state={data:null,range:30,metric:'impressions',query:'',sort:'impressions',direction:-1,showAll:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

function csvRows(text){const out=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x!==''))out.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);out.push(row)}return out}
function parseDate(s){const [d,m,y]=s.split('/').map(Number);return new Date(y,m-1,d)}
function siteFromUrl(raw){try{const value=raw.includes('resource_id=')?decodeURIComponent(raw.split('resource_id=')[1].split('&')[0]):raw;const url=new URL(value);return {url:value,name:url.hostname.replace(/^www\./,'')}}catch{return {url:raw,name:raw}}}
function parseMetric(text){const rows=csvRows(text),headers=rows[0].slice(1);return {dates:headers.map(parseDate),rows:rows.slice(1).map(row=>({site:siteFromUrl(row[0]),values:headers.map((_,i)=>row[i+1]===''||row[i+1]==null?null:Number(row[i+1]))}))}}
async function loadData(){setBusy(true);try{const entries=await Promise.all(Object.entries(SOURCES).map(async([key,gid])=>{const url=`https://docs.google.com/spreadsheets/d/e/${SHEET_ID}/pub?output=csv&gid=${gid}&cache=${Date.now()}`;const response=await fetch(url);if(!response.ok)throw new Error(`Could not load ${key}`);return [key,parseMetric(await response.text())]}));const metrics=Object.fromEntries(entries);const properties=new Map();Object.entries(metrics).forEach(([metric,data])=>data.rows.forEach(row=>{if(!properties.has(row.site.url))properties.set(row.site.url,{...row.site});properties.get(row.site.url)[metric]=row.values}));const dates=metrics.impressions.dates;let latest=-1;dates.forEach((_,i)=>{if([...properties.values()].some(p=>p.impressions?.[i]!=null))latest=i});state.data={dates,latest,properties:[...properties.values()]};render();toast('Live sheet data refreshed')}catch(err){console.error(err);toast('Could not load the published sheet');$('#heroSubtitle').textContent='The published Google Sheet could not be reached. Try refreshing.'}finally{setBusy(false)}}
function setBusy(on){$('#refreshButton').style.transform=on?'rotate(45deg)':'';$('#refreshButton').disabled=on}
function indices(){const end=state.data.latest+1,start=state.range==='all'?0:Math.max(0,end-state.range);return {start,end,prevStart:Math.max(0,start-(end-start)),prevEnd:start}}
function filtered(){const q=state.query.toLowerCase();return state.data.properties.filter(p=>p.name.toLowerCase().includes(q)||p.url.toLowerCase().includes(q))}
function sumRange(values,start,end){return (values||[]).slice(start,end).reduce((a,v)=>a+(v??0),0)}
function avgRange(values,start,end){const vals=(values||[]).slice(start,end).filter(v=>v!=null&&v!==0);return vals.length?vals.reduce((a,v)=>a+v,0)/vals.length:0}
function aggregate(metric,props,start,end){const result=[];for(let i=start;i<end;i++){if(metric==='position'){const vals=props.map(p=>p.position?.[i]).filter(v=>v!=null&&v!==0);result.push(vals.length?vals.reduce((a,v)=>a+v,0)/vals.length:0)}else if(metric==='ctr'){const imp=props.reduce((a,p)=>a+(p.impressions?.[i]||0),0),click=props.reduce((a,p)=>a+(p.clicks?.[i]||0),0);result.push(imp?click/imp*100:0)}else result.push(props.reduce((a,p)=>a+(p[metric]?.[i]||0),0))}return result}
function formatNumber(n,dec=0){if(!Number.isFinite(n))return '—';if(Math.abs(n)>=1e6)return `${(n/1e6).toFixed(1)}M`;if(Math.abs(n)>=1e3)return `${(n/1e3).toFixed(n>=10000?1:2)}K`;return n.toLocaleString('en-GB',{maximumFractionDigits:dec})}
function pct(current,previous,invert=false){if(!previous)return {value:0,text:'0.0%',good:true};const value=(current-previous)/Math.abs(previous)*100;return {value,text:`${Math.abs(value).toFixed(1)}%`,good:invert?value<=0:value>=0}}
function pathFor(values,w=110,h=30,pad=2){const max=Math.max(...values,1),min=Math.min(...values),span=max-min||1;return values.map((v,i)=>`${i?'L':'M'}${pad+i*(w-pad*2)/Math.max(values.length-1,1)},${h-pad-(v-min)/span*(h-pad*2)}`).join(' ')}
function spark(svg,values,color){svg.innerHTML=`<path d="${pathFor(values)}" fill="none" stroke="${color}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="${pathFor(values)} L108,30 L2,30Z" fill="${color}" opacity=".08"/>`}
function metricSummary(metric,props,idx){if(metric==='position')return avgRange(aggregate('position',props,0,state.data.dates.length),idx.start,idx.end);if(metric==='ctr'){const imp=props.reduce((a,p)=>a+sumRange(p.impressions,idx.start,idx.end),0),click=props.reduce((a,p)=>a+sumRange(p.clicks,idx.start,idx.end),0);return imp?click/imp*100:0}return props.reduce((a,p)=>a+sumRange(p[metric],idx.start,idx.end),0)}
function renderKpis(props,idx){['impressions','clicks','position','ctr'].forEach(metric=>{const cur=metricSummary(metric,props,idx),prev=metricSummary(metric,props,{start:idx.prevStart,end:idx.prevEnd}),change=pct(cur,prev,metric==='position');const prefix={impressions:'imp',clicks:'click',position:'pos',ctr:'ctr'}[metric];$(`#${prefix}Value`).textContent=metric==='ctr'?`${cur.toFixed(2)}%`:metric==='position'?cur.toFixed(1):formatNumber(cur);const pill=$(`#${prefix}Trend`);pill.textContent=`${change.value>=0?'↑':'↓'} ${change.text}`;pill.classList.toggle('down',!change.good);const vals=aggregate(metric,props,idx.start,idx.end);spark($(`#${prefix}Spark`),vals,COLORS[metric]);$(`#${prefix}Compare`).textContent=idx.prevEnd>idx.prevStart?`${change.good?'Improved':'Changed'} vs previous period`:metric==='position'?'lower is better':metric==='ctr'?'clicks ÷ impressions':'selected period'})}
function renderChart(props,idx){const svg=$('#mainChart'),values=aggregate(state.metric,props,idx.start,idx.end),prev=aggregate(state.metric,props,idx.prevStart,idx.prevEnd);const W=1100,H=270,left=50,right=12,top=16,bottom=34;const all=[...values,...prev],max=Math.max(...all,1),min=state.metric==='position'?Math.min(...all.filter(Boolean),0):0,span=max-min||1;const x=i=>left+i*(W-left-right)/Math.max(values.length-1,1),y=v=>top+(max-v)/span*(H-top-bottom);let html='';for(let i=0;i<5;i++){const yy=top+i*(H-top-bottom)/4,val=max-i*span/4;html+=`<line x1="${left}" x2="${W-right}" y1="${yy}" y2="${yy}" stroke="#edf0ed"/><text x="${left-9}" y="${yy+3}" text-anchor="end" fill="#9aa49f" font-size="9">${state.metric==='ctr'?val.toFixed(1)+'%':formatNumber(val,1)}</text>`}const line=(arr,dashed=false)=>arr.length?`<path d="${arr.map((v,i)=>`${i?'L':'M'}${x(i)},${y(v)}`).join(' ')}" fill="none" stroke="${dashed?'#b7c1bb':COLORS[state.metric]}" stroke-width="${dashed?1.5:2.5}" ${dashed?'stroke-dasharray="5 5"':''} stroke-linejoin="round" stroke-linecap="round"/>`:'';html+=line(prev,true)+line(values);const labelStep=Math.max(1,Math.floor(values.length/6));values.forEach((v,i)=>{if(i%labelStep===0||i===values.length-1){const d=state.data.dates[idx.start+i];html+=`<text x="${x(i)}" y="${H-8}" text-anchor="middle" fill="#98a19d" font-size="9">${d.toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</text>`}html+=`<circle class="chart-hit" data-i="${i}" cx="${x(i)}" cy="${y(v)}" r="8" fill="transparent"/><circle cx="${x(i)}" cy="${y(v)}" r="${i===values.length-1?3:0}" fill="${COLORS[state.metric]}" stroke="white" stroke-width="2"/>`});svg.innerHTML=html;$$('.chart-hit').forEach(hit=>hit.addEventListener('mouseenter',e=>{const i=Number(e.target.dataset.i),d=state.data.dates[idx.start+i],tip=$('#chartTooltip'),v=values[i];tip.innerHTML=`${d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}<strong>${state.metric==='ctr'?v.toFixed(2)+'%':state.metric==='position'?v.toFixed(1):formatNumber(v)}</strong>`;tip.hidden=false;tip.style.left=`${Math.min(90,Math.max(3,(i/Math.max(values.length-1,1))*90))}%`;tip.style.top=`${Math.max(5,(y(v)/H)*80)}%`}).bind(null));$$('.chart-hit').forEach(hit=>hit.addEventListener('mouseleave',()=>$('#chartTooltip').hidden=true))}
function propertyStats(p,idx){const imp=sumRange(p.impressions,idx.start,idx.end),clicks=sumRange(p.clicks,idx.start,idx.end),position=avgRange(p.position,idx.start,idx.end),prevImp=sumRange(p.impressions,idx.prevStart,idx.prevEnd);return {imp,clicks,position,ctr:imp?clicks/imp*100:0,movement:pct(imp,prevImp).value}}
function renderTable(props,idx){let rows=props.map(p=>({p,s:propertyStats(p,idx)}));rows.sort((a,b)=>{const av=state.sort==='name'?a.p.name:a.s[state.sort],bv=state.sort==='name'?b.p.name:b.s[state.sort];return (av>bv?1:av<bv?-1:0)*state.direction});const visible=state.showAll?rows:rows.slice(0,7);$('#propertyRows').innerHTML=visible.length?visible.map(({p,s})=>{const vals=(p.impressions||[]).slice(Math.max(0,idx.end-30),idx.end).map(v=>v||0);return `<tr><td><div class="property-cell"><span class="favicon">${p.name[0]}</span><span class="property-name"><strong>${p.name}</strong><small>${p.url}</small></span></div></td><td><span class="value-strong">${formatNumber(s.imp)}</span><span class="movement ${s.movement<0?'negative':''}">${s.movement>=0?'↑':'↓'} ${Math.abs(s.movement).toFixed(0)}%</span></td><td class="value-strong">${formatNumber(s.clicks)}</td><td>${s.ctr.toFixed(2)}%</td><td>${s.position?s.position.toFixed(1):'—'}</td><td><svg class="row-spark" viewBox="0 0 80 24"><path d="${pathFor(vals,80,24)}" fill="none" stroke="${s.movement>=0?'#4e8a68':'#c47a5d'}" stroke-width="1.6"/></svg></td><td><a class="open-link" target="_blank" rel="noopener" href="${p.url}">↗</a></td></tr>`}).join(''):'<tr><td colspan="7" class="loading-row">No properties match this search.</td></tr>';$('#viewAllButton').innerHTML=state.showAll?'Show top 7 <span>↑</span>':'View all <span>→</span>'}
function render(){if(!state.data)return;const idx=indices(),props=filtered(),latest=state.data.dates[state.data.latest],rangeText=state.range==='all'?'all recorded history':`the last ${state.range} days`;$('#navCount').textContent=state.data.properties.length;$('#sidebarLatest').textContent=latest.toLocaleDateString('en-GB',{day:'numeric',month:'short'});$('#heroSubtitle').textContent=`Monitoring ${props.length} web ${props.length===1?'property':'properties'} across ${rangeText}. Data through ${latest.toLocaleDateString('en-GB',{day:'numeric',month:'long'})}.`;$('#updatedText').textContent=`Updated from Sheets · ${latest.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}`;renderKpis(props,idx);renderChart(props,idx);renderTable(props,idx)}
function exportCsv(){if(!state.data)return;const idx=indices(),lines=[['Property','Impressions','Clicks','CTR','Average position']];filtered().forEach(p=>{const s=propertyStats(p,idx);lines.push([p.url,s.imp,s.clicks,s.ctr.toFixed(3),s.position.toFixed(2)])});const blob=new Blob([lines.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`gsc-performance-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);toast('CSV export downloaded')}
let toastTimer;function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
$('#rangeSelect').addEventListener('change',e=>{state.range=e.target.value==='all'?'all':Number(e.target.value);render()});$$('.metric-tabs button').forEach(b=>b.addEventListener('click',()=>{$$('.metric-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.metric=b.dataset.metric;render()}));function search(value){state.query=value;$('#globalSearch').value=value;$('#tableSearch').value=value;render()}$('#globalSearch').addEventListener('input',e=>search(e.target.value));$('#tableSearch').addEventListener('input',e=>search(e.target.value));$('#refreshButton').addEventListener('click',loadData);$('#exportButton').addEventListener('click',exportCsv);$('#viewAllButton').addEventListener('click',()=>{state.showAll=!state.showAll;render()});$$('.sort-button').forEach(b=>b.addEventListener('click',()=>{if(state.sort===b.dataset.sort)state.direction*=-1;else{state.sort=b.dataset.sort;state.direction=b.dataset.sort==='name'?1:-1}render()}));$('[data-open-sheet]').addEventListener('click',()=>window.open(WORKBOOK_URL,'_blank'));$('[data-focus-search]').addEventListener('click',()=>{$('#globalSearch').focus()});document.addEventListener('keydown',e=>{if(e.key==='/'&&!/input|textarea/i.test(e.target.tagName)){e.preventDefault();$('#globalSearch').focus()}});$('.mobile-menu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));loadData();
